### ISSUE TITLE
Missing Create_Upload_Datasets_to_S3.ipynb  in the repo

### ISSUE THREAD

**Issue by codigube** [aws-samples/customer-churn-sagemaker-pipelines-sample#1]
In the **Run Code** section of the README, _Create_Upload_Datasets_to_S3.ipynb_ is mentioned but it is not in the repository.

![image](https://user-images.githubusercontent.com/44806418/157625337-b1e585bd-b4a8-4ffb-8144-18962cc586e5.png)

**Comment by ghanagayatri** [comment]
Updated the instructions
